# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frostfall < Formula
  desc "Accessibility testing made easy"
  homepage "https://github.com/aquia-inc/frostfall"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aquia-inc/frostfall/releases/download/v1.4.0/frostfall_Darwin_x86_64.tar.gz"
      sha256 "5201c80e4467d9f580b68a6da619c0b065e1166769b992e20b4204855378b228"

      define_method(:install) do
        bin.install "frostfall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aquia-inc/frostfall/releases/download/v1.4.0/frostfall_Darwin_arm64.tar.gz"
      sha256 "8bbefdc4fc7e65f74af05fb64f9644596a8be5f6c9aecf2b8f7191084b5a4920"

      define_method(:install) do
        bin.install "frostfall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/frostfall/releases/download/v1.4.0/frostfall_Linux_x86_64.tar.gz"
      sha256 "342fa7b00a1dd8d4b03b57262278d1f44b4250b5370532246be53b8f28d0bf86"
      define_method(:install) do
        bin.install "frostfall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquia-inc/frostfall/releases/download/v1.4.0/frostfall_Linux_arm64.tar.gz"
      sha256 "8e5fc1db9d4439d430cece8f3e94e4c41cc77b2e8eebb0d68587853b14727211"
      define_method(:install) do
        bin.install "frostfall"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frostfall --version")
  end
end
